siteName: iMD App PK
tagline: Medical Resources
whatsappNumber: '923329722201'
telegramHandle: imd_app_pk
supportEmail: support@imdresources.com
youtubeUrl: https://youtube.com/@imdapppk
telegramChannelUrl: https://t.me/imd_app_pk
instagramUrl: https://www.instagram.com/imd_app_pk
facebookUrl: https://www.facebook.com/iMDAppPak
